# render.yaml
services:
  - type: web
    name: sibirskoe-zdorovie
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000